2021-02-03 16:25:04,884 INFO: Microblog startup [in /Users/scottl95/Code/flask_tutorials/microblog/app/__init__.py:44]
2021-02-03 16:28:05,775 INFO: Microblog startup [in /Users/scottl95/Code/flask_tutorials/microblog/app/__init__.py:44]
2021-02-03 16:28:23,597 INFO: Microblog startup [in /Users/scottl95/Code/flask_tutorials/microblog/app/__init__.py:44]
2021-02-03 17:02:25,840 INFO: Microblog startup [in /Users/scottl95/Code/flask_tutorials/microblog/app/__init__.py:44]
2021-02-04 17:52:21,726 INFO: Microblog startup [in /Users/scottl95/Code/flask_tutorials/microblog/app/__init__.py:44]
2021-02-04 18:03:13,234 INFO: Microblog startup [in /Users/scottl95/Code/flask_tutorials/microblog/app/__init__.py:44]
2021-02-04 18:03:29,219 ERROR: Exception on / [GET] [in /Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/scottl95/Code/flask_tutorials/microblog/app/routes.py", line 49, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/scottl95/Code/flask_tutorials/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/scottl95/Code/flask_tutorials/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/scottl95/Code/flask_tutorials/microblog/app/templates/index.html", line 19, in block "content"
    {% include '_posts.html' %}
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _posts.html
2021-02-04 18:03:32,438 ERROR: Exception on /index [GET] [in /Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/scottl95/Code/flask_tutorials/microblog/app/routes.py", line 49, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/scottl95/Code/flask_tutorials/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/scottl95/Code/flask_tutorials/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/scottl95/Code/flask_tutorials/microblog/app/templates/index.html", line 19, in block "content"
    {% include '_posts.html' %}
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _posts.html
2021-02-04 18:03:35,560 ERROR: Exception on /index [GET] [in /Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/scottl95/Code/flask_tutorials/microblog/app/routes.py", line 49, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/scottl95/Code/flask_tutorials/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/scottl95/Code/flask_tutorials/microblog/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/scottl95/Code/flask_tutorials/microblog/app/templates/index.html", line 19, in block "content"
    {% include '_posts.html' %}
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/scottl95/Code/python/env38/lib/python3.8/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: _posts.html
